import type { GenerateOptions } from '../index.js';

type AuthOptions = NonNullable<GenerateOptions['auth']>;

export function generatePackageJson(options: { name: string; typescript: boolean }) {
  const { name, typescript } = options;
  return {
    name: `mcp-server-${name.replace(/\s+/g, '-').toLowerCase()}`,
    version: '1.0.0',
    description: `MCP server for ${name} — generated by mcp-bridge`,
    private: true,
    type: 'module',
    main: typescript ? 'dist/index.js' : 'index.js',
    scripts: typescript
      ? {
          build: 'tsc',
          start: 'node dist/index.js',
          dev: 'tsc && node dist/index.js',
        }
      : {
          start: 'node index.js',
        },
    dependencies: {
      '@modelcontextprotocol/sdk': '^1.0.0',
      zod: '^3.23.0',
    },
    devDependencies: typescript
      ? {
          typescript: '^5.4.0',
          '@types/node': '^20.14.0',
        }
      : {},
    engines: { node: '>=18.0.0' },
  };
}
