import type { GenerateOptions } from '../index.js';

interface ReadmeOptions {
  name: string;
  baseUrl: string;
  toolCount: number;
  toolNames: string[];
  auth: NonNullable<GenerateOptions['auth']>;
}

export function generateReadme(options: ReadmeOptions): string {
  const { name, baseUrl, toolCount, toolNames, auth } = options;

  const authSection =
    auth.type === 'none'
      ? ''
      : `## Auth

Set the \`${auth.env || 'API_TOKEN'}\` environment variable before starting the server:

\`\`\`bash
export ${auth.env || 'API_TOKEN'}=your_token_here
\`\`\`
`;

  const toolList = toolNames
    .slice(0, 20)
    .map((t) => `- \`${t}\``)
    .join('\n');

  const moreTools = toolNames.length > 20 ? `\n...and ${toolNames.length - 20} more.` : '';

  return `# MCP Server: ${name}

Generated by [mcp-bridge](https://github.com/yourusername/mcp-bridge).

- **API Base URL:** \`${baseUrl}\`
- **Tools:** ${toolCount}

## Setup

\`\`\`bash
npm install
npm run build   # (TypeScript only)
\`\`\`

${authSection}
## Connect to Claude Desktop

Add this to your \`claude_desktop_config.json\`:

\`\`\`json
{
  "mcpServers": {
    "${name}": {
      "command": "node",
      "args": ["${process.cwd()}/dist/index.js"]${auth.type !== 'none' ? `,\n      "env": {\n        "${auth.env || 'API_TOKEN'}": "your_token_here"\n      }` : ''}
    }
  }
}
\`\`\`

## Available Tools

${toolList}${moreTools}

---
_Generated by [mcp-bridge](https://github.com/yourusername/mcp-bridge)_
`;
}
