import type { ParsedSpec, ParsedEndpoint } from '../parsers/openapi.js';
import type { GenerateOptions } from '../index.js';

interface ServerOptions {
  name: string;
  endpoints: ParsedEndpoint[];
  parsed: ParsedSpec;
  auth: NonNullable<GenerateOptions['auth']>;
  typescript: boolean;
  toolNames: string[];
}

export async function generateMCPServer(options: ServerOptions): Promise<string> {
  const { name, endpoints, parsed, auth, typescript, toolNames } = options;

  const imports = toolNames.map((t) => `import { ${t}Tool } from './tools/${t}.js';`).join('\n');

  const toolRegistrations = endpoints.map((ep) => {
    const zodParams = buildZodParams(ep);

    return `
  server.tool(
    '${ep.operationId}',
    \`${escapeTemplate(ep.summary || ep.description || ep.operationId)}\`,
    {${zodParams}
    },
    async (params) => {
      const result = await ${ep.operationId}Tool(params);
      return {
        content: [
          {
            type: 'text',
            text: typeof result === 'string' ? result : JSON.stringify(result, null, 2),
          },
        ],
      };
    }
  );`;
  }).join('\n');

  const ts = typescript;

  return `#!/usr/bin/env node
/**
 * MCP Server: ${parsed.info.title}
 * Generated by mcp-bridge — https://github.com/yourusername/mcp-bridge
 *
 * API Version: ${parsed.info.version}
 * Base URL: ${parsed.baseUrl}
 * Tools: ${endpoints.length}
 */

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
${imports}

const server = new McpServer({
  name: '${name}',
  version: '1.0.0',
  description: \`${escapeTemplate(parsed.info.description || parsed.info.title)}\`,
});

// ─── Tool Registrations ────────────────────────────────────────────────────
${toolRegistrations}

// ─── Start Server ─────────────────────────────────────────────────────────

async function main()${ts ? ': Promise<void>' : ''} {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error('[${name}] MCP server started');
}

main().catch((err) => {
  console.error('[${name}] Fatal error:', err);
  process.exit(1);
});
`;
}

function buildZodParams(ep: ParsedEndpoint): string {
  const params: string[] = [];

  for (const param of ep.parameters) {
    const zodType = jsonSchemaToZod(param.schema);
    const required = param.required;
    const description = param.description ? `.describe(${JSON.stringify(param.description)})` : '';
    const optional = required ? '' : '.optional()';
    params.push(`\n      ${JSON.stringify(param.name)}: ${zodType}${description}${optional},`);
  }

  if (ep.requestBody) {
    const zodType = jsonSchemaToZod(ep.requestBody.schema);
    const description = ep.requestBody.description
      ? `.describe(${JSON.stringify(ep.requestBody.description)})`
      : '';
    const optional = ep.requestBody.required ? '' : '.optional()';
    params.push(`\n      body: ${zodType}${description}${optional},`);
  }

  return params.join('');
}

export function jsonSchemaToZod(schema: Record<string, unknown>): string {
  if (!schema || typeof schema !== 'object') return 'z.unknown()';

  const type = schema.type as string;

  if (schema.enum) {
    const values = (schema.enum as unknown[]).map((v) => JSON.stringify(v));
    return `z.enum([${values.join(', ')}])`;
  }

  if (schema.anyOf || schema.oneOf) {
    const union = ((schema.anyOf || schema.oneOf) as Record<string, unknown>[])
      .map(jsonSchemaToZod)
      .join(', ');
    return `z.union([${union}])`;
  }

  if (schema.allOf) {
    // Simplified: just use the first schema
    return jsonSchemaToZod((schema.allOf as Record<string, unknown>[])[0]);
  }

  switch (type) {
    case 'string': {
      let z = 'z.string()';
      if (schema.format === 'date-time') z += ".datetime({ offset: true })";
      if (schema.format === 'email') z += ".email()";
      if (schema.format === 'uri' || schema.format === 'url') z += ".url()";
      if (schema.format === 'uuid') z += ".uuid()";
      if (schema.minLength != null) z += `.min(${schema.minLength})`;
      if (schema.maxLength != null) z += `.max(${schema.maxLength})`;
      if (schema.pattern) z += `.regex(/${schema.pattern}/)`;
      return z;
    }

    case 'integer':
      return `z.number().int()${schema.minimum != null ? `.min(${schema.minimum})` : ''}${schema.maximum != null ? `.max(${schema.maximum})` : ''}`;

    case 'number':
      return `z.number()${schema.minimum != null ? `.min(${schema.minimum})` : ''}${schema.maximum != null ? `.max(${schema.maximum})` : ''}`;

    case 'boolean':
      return 'z.boolean()';

    case 'array': {
      const items = schema.items
        ? jsonSchemaToZod(schema.items as Record<string, unknown>)
        : 'z.unknown()';
      return `z.array(${items})`;
    }

    case 'object': {
      if (!schema.properties) return 'z.record(z.string(), z.unknown())';
      const required = new Set((schema.required as string[]) || []);
      const props = Object.entries(schema.properties as Record<string, unknown>)
        .map(([key, val]) => {
          const zodVal = jsonSchemaToZod(val as Record<string, unknown>);
          return `${JSON.stringify(key)}: ${zodVal}${required.has(key) ? '' : '.optional()'}`;
        })
        .join(', ');
      return `z.object({ ${props} })`;
    }

    case 'null':
      return 'z.null()';

    default:
      if (schema.properties) {
        return jsonSchemaToZod({ ...schema, type: 'object' });
      }
      return 'z.unknown()';
  }
}

function escapeTemplate(str: string): string {
  return str.replace(/`/g, "'").replace(/\$\{/g, '\\${');
}
