import type { ParsedEndpoint, ParsedSpec } from '../parsers/openapi.js';
import type { GenerateOptions } from '../index.js';

interface ToolOptions {
  typescript: boolean;
  auth: NonNullable<GenerateOptions['auth']>;
}

interface GeneratedTool {
  name: string;
  code: string;
}

export async function generateTools(
  endpoint: ParsedEndpoint,
  spec: ParsedSpec,
  options: ToolOptions
): Promise<GeneratedTool> {
  const { typescript, auth } = options;
  const { operationId, method, path: apiPath, parameters, requestBody, summary, description } = endpoint;

  const ts = typescript;

  // Build the parameter type
  const paramFields = parameters.map((p) => {
    const optional = p.required ? '' : '?';
    return `  ${p.name}${optional}: ${jsonSchemaToTs(p.schema)};`;
  });

  if (requestBody) {
    const optional = requestBody.required ? '' : '?';
    paramFields.push(`  body${optional}: ${jsonSchemaToTs(requestBody.schema)};`);
  }

  const typeDecl = ts && paramFields.length > 0
    ? `\ninterface Params {\n${paramFields.join('\n')}\n}\n`
    : '';

  // Build URL construction
  let urlExpr = `\`${spec.baseUrl.replace(/\/$/, '')}${apiPath.replace(/\{([^}]+)\}/g, '${params.$1}')}\``;

  // Build query string
  const queryParams = parameters.filter((p) => p.in === 'query');
  let queryBuilder = '';
  if (queryParams.length > 0) {
    queryBuilder = `
  const query = new URLSearchParams();
  ${queryParams
    .map((p) => {
      if (p.required) {
        return `query.set('${p.name}', String(params['${p.name}']));`;
      }
      return `if (params['${p.name}'] != null) query.set('${p.name}', String(params['${p.name}']));`;
    })
    .join('\n  ')}
  const qs = query.toString();`;
    urlExpr = `${urlExpr} + (qs ? '?' + qs : '')`;
  }

  // Build auth header
  let authHeader = '';
  switch (auth.type) {
    case 'bearer':
      authHeader = `'Authorization': \`Bearer \${process.env.${auth.env || 'API_TOKEN'}}\`,`;
      break;
    case 'api-key':
      authHeader = `'${auth.header || 'X-API-Key'}': process.env.${auth.env || 'API_TOKEN'} || '',`;
      break;
    case 'basic':
      authHeader = `'Authorization': \`Basic \${Buffer.from(\`\${process.env.${auth.env || 'API_USERNAME'}}:\${process.env.${auth.env?.replace('USERNAME', 'PASSWORD') || 'API_PASSWORD'}}\`).toString('base64')}\`,`;
      break;
  }

  // Build request body
  const hasBody = method.toLowerCase() !== 'get' && method.toLowerCase() !== 'head' && method.toLowerCase() !== 'delete';
  const bodySection = hasBody && requestBody
    ? `body: JSON.stringify(params.body),`
    : '';

  const code = `/**
 * MCP Tool: ${operationId}
 * ${summary || description || `${method.toUpperCase()} ${apiPath}`}
 *
 * Generated by mcp-bridge — https://github.com/yourusername/mcp-bridge
 */
${typeDecl}
export async function ${operationId}Tool(params${ts ? ': Params' : ''})${ts ? ': Promise<unknown>' : ''} {${queryBuilder}
  const url = ${urlExpr};

  const response = await fetch(url, {
    method: '${method.toUpperCase()}',
    headers: {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
      ${authHeader}
    },
    ${bodySection}
  });

  if (!response.ok) {
    const errorText = await response.text().catch(() => 'Unknown error');
    throw new Error(\`${operationId} failed (\${response.status}): \${errorText}\`);
  }

  const contentType = response.headers.get('content-type') || '';
  if (contentType.includes('application/json')) {
    return response.json();
  }
  return response.text();
}
`;

  return { name: operationId, code };
}

function jsonSchemaToTs(schema: Record<string, unknown>): string {
  if (!schema || typeof schema !== 'object') return 'unknown';

  const type = schema.type as string;

  if (schema.enum) {
    return (schema.enum as unknown[]).map((v) => JSON.stringify(v)).join(' | ');
  }

  if (schema.anyOf || schema.oneOf) {
    const union = ((schema.anyOf || schema.oneOf) as Record<string, unknown>[])
      .map(jsonSchemaToTs)
      .join(' | ');
    return union;
  }

  switch (type) {
    case 'string': return 'string';
    case 'integer':
    case 'number': return 'number';
    case 'boolean': return 'boolean';
    case 'null': return 'null';
    case 'array': {
      const items = schema.items ? jsonSchemaToTs(schema.items as Record<string, unknown>) : 'unknown';
      return `${items}[]`;
    }
    case 'object': {
      if (!schema.properties) return 'Record<string, unknown>';
      const required = new Set((schema.required as string[]) || []);
      const props = Object.entries(schema.properties as Record<string, unknown>)
        .map(([k, v]) => {
          const opt = required.has(k) ? '' : '?';
          return `${k}${opt}: ${jsonSchemaToTs(v as Record<string, unknown>)}`;
        })
        .join('; ');
      return `{ ${props} }`;
    }
    default:
      if (schema.properties) return jsonSchemaToTs({ ...schema, type: 'object' });
      return 'unknown';
  }
}
